version: "3"
services:

  db:
    build: ./mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  python:
    build: ./python
    volumes:
      - ./python:/var/www/
      - ./src:/var/www/src
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
    links:
      - db

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - python
    ports:
      - "4231:80"
    environment:
      TZ: "Asia/Tokyo"

